package composer

import (
	"fmt"
	"sort"

	"github.com/vailang/vai/internal/compiler/ast"
)

// ASTSource provides parsed AST files to the composer.
type ASTSource interface {
	Files() []*ast.File
}

// SymbolResolver provides external symbol information from the host file.
// Implementations typically wrap the coder package.
type SymbolResolver interface {
	// Symbols returns a map of external symbol names to their kinds.
	Symbols() map[string]ast.SymbolKind
	// Signatures returns a map of symbol names to their rendered signatures.
	Signatures() map[string]string
	// GetCode returns the source code for a named symbol.
	GetCode(name string) (string, bool)
	// GetDoc returns the documentation for a named symbol.
	GetDoc(name string) (string, bool)
	// IsGenerated returns true if the symbol was generated by vai (inside vai:output markers).
	IsGenerated(name string) bool
}

// TargetResolver resolves symbols from target files via the coder package.
// Implementations wrap coder.New(lang, filePath) to extract symbols.
type TargetResolver interface {
	// ResolveTarget parses the target file and returns its symbols and signatures.
	ResolveTarget(path string) (symbols map[string]ast.SymbolKind, sigs map[string]string, err error)
	// GetCode returns the source code for a named symbol in the target file.
	GetCode(path, name string) (string, bool)
	// GetDoc returns the documentation for a named symbol in the target file.
	GetDoc(path, name string) (string, bool)
}

// Error represents a semantic validation error with position.
type Error struct {
	Msg string
	Pos ast.Position
}

func (e Error) Error() string {
	return fmt.Sprintf("%d:%d: %s", e.Pos.Line, e.Pos.Column, e.Msg)
}

// RequestType classifies the kind of work a request represents.
type RequestType string

const (
	PlannerAgent  RequestType = "planner"  // plan declaration → needs planning
	ExecutorAgent RequestType = "executor" // func/struct/interface/type → needs LLM execution
)

// Reference represents a resolved [use X] dependency within a request.
type Reference struct {
	Name         string         // "User", "User.IsActive"
	Kind         ast.SymbolKind // symbol kind if external, empty if internal AST
	Signature    string         // resolved signature from host
	AppendCode   bool           // +code modifier
	AppendDoc    bool           // +doc modifier
	IsExternal   bool           // true if resolved from host symbols, false if from AST
	IsGenerated  bool           // true if symbol was vai-generated (inside vai:output markers)
	ResolvedCode string         // actual host source code (when +code)
	ResolvedDoc  string         // host documentation (when +doc)
}

// ExternalSymbol is now defined in ast.ExternalSymbol.
// // ExternalSymbol describes a host file symbol visible to the plan.
// type ExternalSymbol struct {
// 	Name        string         `json:"name"`
// 	Kind        ast.SymbolKind `json:"kind"`
// 	Signature   string         `json:"signature"`
// 	IsGenerated bool           `json:"is_generated"`
// }

// Request represents a resolved task ready for the planner/executor pipeline.
type Request struct {
	Name       string      // declaration name
	Task       string      // signature + description (prompt text)
	References []Reference // all resolved [use X] dependencies
	Type       RequestType // PlannerAgent or ExecutorAgent
}

// Composer validates the semantic correctness of parsed AST files
// and produces resolved requests for the execution pipeline.
type Composer struct {
	src            ASTSource
	resolver       SymbolResolver
	targetResolver TargetResolver
	symbols        map[string]ast.SymbolKind
	knownPrompts   map[string]bool // qualified prompt names (e.g. "std.executor_role")
	errors         []Error

	// declared maps symbol names to their declarations across all files.
	declared map[string]ast.Declaration

	// targetSymbols and targetSigs are populated from target files during validation.
	targetSymbols map[string]ast.SymbolKind
	targetSigs    map[string]string
	targetPaths   []string // resolved target file paths
}

// New creates a new Composer.
// resolver provides external symbol information (from host file header parsing).
// targetResolver provides symbol information from target files (via coder).
// knownPrompts is a set of qualified prompt names for [inject X.Y] validation.
// Pass nil for any parameter if not available.
func New(src ASTSource, resolver SymbolResolver, targetResolver TargetResolver, knownPrompts map[string]bool) *Composer {
	var symbols map[string]ast.SymbolKind
	if resolver != nil {
		symbols = resolver.Symbols()
	}
	return &Composer{
		src:            src,
		resolver:       resolver,
		targetResolver: targetResolver,
		symbols:        symbols,
		knownPrompts:   knownPrompts,
	}
}

// ExternalSymbols returns all host file symbols with their signatures.
// When a plan has a target, these should be included in the Plan for LLM context.
func (c *Composer) ExternalSymbols() []ast.ExternalSymbol {
	if c.resolver == nil {
		return nil
	}
	sigs := c.resolver.Signatures()
	symbols := c.resolver.Symbols()
	if len(symbols) == 0 {
		return nil
	}

	result := make([]ast.ExternalSymbol, 0, len(symbols))
	for name, kind := range symbols {
		result = append(result, ast.ExternalSymbol{
			Name:      name,
			Kind:      string(kind),
			Signature: sigs[name],
		})
	}
	sort.Slice(result, func(i, j int) bool {
		return result[i].Name < result[j].Name
	})
	return result
}

// buildDeclaredMap indexes all declarations from all files by name.
func (c *Composer) buildDeclaredMap() {
	c.declared = make(map[string]ast.Declaration)
	for _, file := range c.src.Files() {
		for _, decl := range file.Declarations {
			name := decl.DeclName()
			if name != "" && name[0] != '_' {
				c.declared[name] = decl
			}

			switch d := decl.(type) {
			case *ast.StructDecl:
				for _, m := range d.Methods {
					c.declared[d.Name+"."+m.Name] = m
				}
			case *ast.InterfaceDecl:
				for _, m := range d.Methods {
					c.declared[d.Name+"."+m.Name] = m
				}
			case *ast.PlanDecl:
				for _, inner := range d.Declarations {
					innerName := inner.DeclName()
					if innerName != "" && innerName[0] != '_' {
						c.declared[innerName] = inner
					}
				}
			}
		}
	}
}
